#!/bin/sh
# Refreshes bracino_build_id.h with the CURRENT tree identity.
# Runs on every ninja build (custom target). Writes only when content
# changes so unchanged trees don't trigger recompiles.
#
# Why not CMake add_compile_definitions: cmake re-configures only when
# CMakeLists.txt changes — a stale alias reached a flashed bin (2026-09-02,
# bin said 557168a-m while the tree was 604974d clean). Identity must be
# computed per build, not per configure.
#
# $1 = output dir (build/)
OUT="$1/bracino_build_id.h"
cd "$(dirname "$0")" || exit 1

HASH=$(git rev-parse --short HEAD 2>/dev/null || echo dev)
# dirty = uncommitted changes to this firmware dir only (untracked files
# like logs don't count); scope matches what actually produced the bin
if ! git diff --quiet -- . 2>/dev/null; then
    HASH="${HASH}-m"
fi
STAMP=$(date -u +%Y%m%d.%H%M)

cat > "$OUT.tmp" <<EOF
/* AUTO-GENERATED by gen_build_id.sh — do not edit or commit.
 * Deterministic identity of the exact source tree flashed to the device. */
#ifndef BRACINO_BUILD_ID_H
#define BRACINO_BUILD_ID_H
#define BRACINO_BUILD      "$STAMP"
#define BRACINO_BUILD_NAME "$HASH"
#endif
EOF

cmp -s "$OUT.tmp" "$OUT" 2>/dev/null || mv "$OUT.tmp" "$OUT"
rm -f "$OUT.tmp"
